server:
  port: 8084
spring:
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/matches
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 5
  logging:
    pattern.console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
    level.org.hibernate.SQL: debug
    level: debug

statsbomb:
  loadDatabase: false