server:
  port: 8081
spring:
  application:
      name: competitions-rest
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/competitions
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 5
  logging:
    pattern.console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
    level.org.hibernate.SQL: debug
    level: debug


statsbomb:
  loadDatabase: false
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 30