server:
  port: 8081
spring:
  application:
    name: competitions
  jpa.hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/competitions
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 5
  logging:
    pattern.console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
    level.org.hibernate.SQL: debug
    level: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

statsbomb:
  loadDatabase: false
